"""Render the metric table in docs/data_coverage.md from docs/data_coverage.yaml (the YAML is the source of truth).

    python tests/render_coverage.py                  # rewrite the table block in place
    python tests/render_coverage.py --check  # exit 1 if the committed table is stale

tests/test_data_coverage.py runs the equivalent of --check, so the markdown can never drift from the matrix.
Lives under tests/ because it needs PyYAML (a dev-only dependency); the application never imports it.
"""

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = ROOT / "docs" / "data_coverage.yaml"
MD_PATH = ROOT / "docs" / "data_coverage.md"
BEGIN, END = "<!-- BEGIN METRIC TABLE (generated by tests/render_coverage.py) -->", "<!-- END METRIC TABLE -->"


def _cell(text: object) -> str:
    return str(text if text is not None else "").replace("|", "\\|").replace("\n", " ").strip()


def render_table(data: dict) -> str:
    lines = []
    by_category: dict[str, list[dict]] = {}
    for metric in data["metrics"]:
        by_category.setdefault(metric["category"], []).append(metric)
    for category, entries in by_category.items():
        lines += [
            f"#### {category}",
            "",
            "| metric | status | source / command | direct or derived | live-tested |",
            "|---|---|---|---|---|",
        ]
        for m in entries:
            tested = "yes: " + ", ".join(m["sample_tested"]["symbols"][:6]) if m["sample_tested"]["live"] else "no"
            lines.append(
                f"| `{m['metric']}` | {m['status']} | {_cell(m['provider'])}: {_cell(m['command'])[:110]} "
                f"| {m['direct_or_derived']} | {_cell(tested)} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def rendered_markdown(markdown: str, data: dict) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    block = f"{BEGIN}\n\n{render_table(data)}\n{END}"
    if not pattern.search(markdown):
        raise SystemExit("markers not found in docs/data_coverage.md")
    return pattern.sub(lambda _: block, markdown)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = yaml.safe_load(YAML_PATH.read_text(encoding="utf-8"))
    current = MD_PATH.read_text(encoding="utf-8")
    updated = rendered_markdown(current, data)
    if args.check:
        if updated != current:
            print("docs/data_coverage.md is stale: run python tests/render_coverage.py")
            return 1
        return 0
    MD_PATH.write_text(updated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
